USE nttdata_javajdbc;

DROP TABLE hibernate_customer;

CREATE TABLE hibernate_customer (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    LASTNAME1 VARCHAR(50) NOT NULL,
    LASTNAME2 VARCHAR(50) NOT NULL,
    IDN VARCHAR(9) NOT NULL UNIQUE,
    AUDIT_UPDATED_USER VARCHAR(50) NOT NULL,
    AUDIT_UPDATED_DATE DATE NOT NULL,
    PRIMARY KEY (ID)
);